from .direct_control_hijacking.direct_control_hijacking import DirectControlHijacking
from .permission_escalation.permission_escalation import PermissionEscalation
from .role_inheritance.role_inheritance import RoleInheritance
from .goal_interpretation.goal_interpretation import GoalInterpretation 